name: nondesu
description: nondescript desktop mascot
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  flutter_acrylic: ^1.1.4
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
